version: '2'

services:
   db:
     image: mysql:5.7
     container_name: wordpress-db-container
     volumes:
       #- db_data:/var/lib/mysql
       - ./data/mysql/conf.d:/etc/mysql/conf.d
       - ./data/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
       - mysql:/var/lib/mysql
     restart: always
     env_file: .env
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     container_name: wordpress-container
     depends_on:
       - db
     ports:
       - "${HOST_PORT}:80"
     restart: always
     volumes:
       - "./wp:/var/www/html"
     env_file: .env
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: wordpress-phpmyadmin-container
     ports:
       - 22222:80

volumes:
    mysql:
