version: '2'

services:
   db:
     image: mysql:5.7
     container_name: wordpress-db-container
     volumes:
       - ./data/mysql:/var/lib/mysql
       #- db_data:/var/lib/mysql
       #- ./data/mysql.sql:/docker-entrypoint-initdb.d/install_wordpress.sql

     restart: always
     env_file: .env

   wordpress:
     image: wordpress:latest
     container_name: wordpress-container
     depends_on:
       - db
     ports:
       - "${HOST_PORT}:80"
     restart: always
     volumes:
       - "./wp:/var/www/html"
     env_file: .env
     environment:
       WORDPRESS_DB_HOST: db:3306
#volumes:
#    db_data:
