version: '3'

services:
   db:
     image: mysql:latest
     container_name: ${PROJECT_NAME}-db
     volumes:
       - ./data/mysql/conf.d:/etc/mysql/conf.d
       - ./data/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
       - mysql:/var/lib/mysql
     command: ['--default_authentication_plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
     restart: always
     ports:
       - "${DB_PORT}:3306"
     env_file: .env
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     container_name: ${PROJECT_NAME}-wordpress
     depends_on:
       - db
     ports:
       - "${HOST_PORT}:80"
     restart: always
     volumes:
       - "./wp:/var/www/html"
     env_file: .env
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_CONFIG_EXTRA: |
         define('WP_HOME','http://localhost:${HOST_PORT}');
         define('WP_SITEURL','http://localhost:${HOST_PORT}');

volumes:
    mysql:
